export const products_data = [
  {
    id: "1",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    img: "Group 575.png",
    price: "9,999",
    discount: "50%",
    before_discount: "9,999",
    brand: "Group 346.svg",
  },
  {
    id: "2",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    img: "Group 583.png",
    price: "9,999",
    discount: null,
    before_discount: null,
    brand: "Group 346.svg",
  },
  {
    id: "3",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    img: "Group 589.png",
    price: "9,999",
    discount: "30%",
    before_discount: "9,999",
    brand: "Group 346.svg",
  },
  {
    id: "4",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    img: "Group 597.png",
    price: "9,999",
    discount: "70%",
    before_discount: "9,999",
    brand: "Group 346.svg",
  },
];
